# application.yaml 은 중요한 정보가 기재되어 있어,
# 깃허브에 파일을 업로드 하지 않는다.
spring:
  application:
    name: SpringCommunity
# h2 의 경우 인텔리제이의 h2 와
# 스프링부트에서 동작하는 db는 각각 분리된 개별 db
# 만약 스프링부트에서 실행하고 싶은 h2 가 있다면
# 스프링부트에서 자동 완성하는 h2를 사용하면 안된다.

  datasource:
#    url: jdbc:h2:mem:community;MODE=MySQL
    # postgresql 을 사용할 것이고 ://주소:port번호/db이름
    url: jdbc:postgresql://localhost:5432/community
    driver-class-name: org.postgresql.Driver
    username: postgres #ql
    password: tjee1234
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: tjoeun.jr5@gmail.com
    password: pozn usov gpld yscl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB # 1개 파일 업로드 가능한 최대 크기
      max-request-size: 5MB # 모든 파일의 크기가 총 5MB까지만 가능
      # 프론트엔드에서 백엔드로 데이터를 넘기고,
      # 백엔드에서 프론트엔드로 전달받은 데이터를 저장할 때
      # 한 파일당 회사에서 업로드 가능하도록 지정한 크기까지만 허용 제한
      # 전체 파일 또한 업로드 가능하도록 지정한 크기까지만 허용 제한
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    session:
      timeout: 30m

# 나의 프로젝트에서 클라이언트가 업로드한 프로필사진을
# 저장하는 폴더 경로
file:
  upload-dir: uploads/profile